### PR TITLE
Proposed tables for storing of calculated volume backscatter data

### PR DESCRIPTION
**Pull request by SverreBerg**

### CODE REVIEW

**Comment by gavinmacaulay** [comment]
There is a draft for gridded data (see under the `Proposed ADCP additions` section - clearly in the wrong section and fixed in commit a4398fc85362ac923a8c939672d841c1c4e53e22), which is towards a similar end as this PR. Can we investigate merging these two contributions into one?

**Comment by lberger29** [comment]
This new subgroup allows to store :

- raw Sv data (eg at sounder samplingrate) together with complex samples in BeamGroup
- averaged Sv data in transducer reference coordinate system

The gridded data subgroup allows to:
-averaged Sv data in either transducer reference coordinate system or absolute reference coordinate system (relative to water line)

I agree that the gridded data allows to store the same data as the calculated volume backscatter and when storing it at the sounder sampling rate using BeamGroup backscatter_r variable with equation type 5 is also possible.

What would be the exact need for this new subgroup?

**Comment by SverreBerg** [comment]
If there are no more coments to the content of this PR.
Would you, Gavin, be kind to help resolving the indicated conflicts and close the PR?

**Comment by gavinmacaulay** [comment]
Will do :)

**Comment by lberger29** [comment]
We have to be carefull not to duplicate the way of storing the same data:
- AveragedVolumeBackscatter is similar to Gridded data which allows multi-channel AveragedVolumeBackscatter (eg same layers for averaging different BeamGroups) and is hence more generic
- VolumeBackscatter is dedicated to store Sv(f) for FM mode as Sv can be stored in BeamGroup for CW mode. Ping based Sv(f) in FM mode can also be stored in Gridded data with grid size equal to ping sampling interval and range_axis_interval_value in GriddedX equal to svf_processing_window_duration in VolumeBackscatter

**Comment by SverreBerg** [comment]
Thanks for the feedback.
I think I need to leave the decision, what is the best way to go, to you experts.

I can confirm that we will be able to store integrated CW backscatter in the GridGroup, for the calculation intervals provided in real-time.
However, there will be some duplicated information about the beams and pulses used. Information already in the BeamGroup.


From our point of view, doing the real-time data collection and processing, the use of a subgroup to the BeamGroup seemed logical.
The duplication of storing single ping CW backscatter in the proposed VolumeBackscatter group (already in the BeamGroup) 
was to handle this data in the same way as single ping FM backscatter.

I did not understand how to store single ping FM backscatter in the GridGroup.
And, does this mean that we would be lacking a way of storing integrated FM backscatter?

**Comment by gavinmacaulay** [comment]
@SverreBerg - I was unable to resolve the conflicts in your branch - git made a new branch with my merge fixes. I think either you need to do the merge conflicts yourself, or I can add my newly created branch (with the merge conflicts resolved) as a new PR and we can move to using that one...

**Comment by SverreBerg** [comment]
@gavinmacaulay - I appreciate if you add your newly created brach as a new PR.

**Comment by lberger29** [comment]
@SverreBerg - I understand that there is a logic logging in real time both raw samples in the beamGroup and averaged data in a subgroup, however doing this at fine scale may create large files
On our side we store raw samples in real time in one file and we store gridded data in separate files at fine scale or larger scale depending on use
You will find in #83 example of gridded data in CW and FM mode on the same line for both DRIX USV and Europe vessel  (data from our work presented at WGFAST in Senegal)

**Comment by SverreBerg** [comment]
@lberger29 - Thanks for pointing me to the example data of gridded data with FM.
From this I can agree that the gridded group may be used, and also in real-time.
With this my proposal in this PR is redundant and may be deleted.
@gavinmacaulay - No need to add your newly created brach as a new PR. Thanks for helping me with GitHub :-)

**Pull request closed without merging**
