### PR TITLE
Proposed vendor specific table for simrad wbt

### PR DESCRIPTION
**Pull request by SverreBerg**
Separate PR for the vendor specific part of the previous PR holding multiple proposals.

### CODE REVIEW

**Comment by gavinmacaulay** [comment]
Was it intended to have this new group as a subgroup of Vendor_specific, or as a new group (as given here)? One of the requirements of the Vendor_specific group is that the contents must not be required to convert backscatter data into Sv or TS, but it looks like the items in the proposed SimradWBT group are necessary for this.

Variables such as the transducer and transceiver impedance are generic enough to be in a Beam_group (with obligation of mandatory if available). The filter coefficients, etc, are probably also generic enough to be in Beam_group also?

**Comment by gavinmacaulay** [comment]
Thanks for the clarification over the more detailed impedances, etc. All that remains is a couple of questions I had in some of my edits, that I think may have been missed:

And some questions/comments:

- I think this group should be a subgroup of Vendor_specific, not a new group under the root level
- Are the coefficients complex numbers?
- Is it intended to have the filter coefficients stored for every ping? 
- It is probably necessary to have some text elsewhere in the convention (or a reference to another document) that explains how to use these coefficients.

**Comment by gavinmacaulay** [comment]
1. I agree to have it as a subgroup of Vendor_specific
1. I suggest to have two variables, one for the real and one for the imaginary parts of the coefficients. This is to make the data variable contents as clear as possible.
2. If the filter coefficients don't change within a file, then I think we don't need to store them for every ping. An alternative is to allow multiple coefficients and provide ping time ranges that they are applicable to. The Vendor_specific group is intended to be very open and allow for storing anything that a vendor thinks is appropriate, so you could include the XML0-filter datagram if desired.
4. I was thinking mainly of the case where the coefficients were structured `real,imag,real,imag,...` and this would become unnecessary if real and imag coefficient variables were used instead.

**Comment by SverreBerg** [comment]
Gavin, after the PR, with SimradWBT, you helped to close.
Do you agree that this PR may be removed?

**Comment by gavinmacaulay** [comment]
Yes, it can be deleted now.

**Pull request closed without merging**
